### ISSUE TITLE
Watcher upgrade

### ISSUE THREAD

**Issue by vschernoff** [protofire/filecoin-CID-checker#118]
Rework the Watcher to handle increasing data volumes

For now lotus server answers for deals request with data size > 1gb - watcher has to process big data every 1 hour - but result answer size is growing

Solution ()
1. Add trugger to lotus server - https://lotus.filecoin.io/storage-providers/configure/configuration/
    it can be looks like this
   Add to lotus server instance settings
   ```
   [some-trigger-settings]
   url=http://filecoin.tools/some-our-handler

   ```
   Add listener by url - which will register all deals one by one in mongo db

**Comment by plcgi1** [comment]
Usefull link
https://pkg.go.dev/github.com/filecoin-project/lotus/chain/events
