### ISSUE TITLE
Set up dev environment

### ISSUE THREAD

**Issue by vschernoff** [protofire/filecoin-CID-checker#124]

**Comment by koteld** [comment]
Local env was set up (MongoDB: mongosh, DB, collection). Agreed to test script on the test node https://calibration.node.glif.io/archive/lotus/rpc/v0 to fetch a reasonable amount of data. Resulting script will be added here: https://github.com/glifio/filecoin-chart/blob/master/templates/sync-s3-marketdeals.yaml
