### ISSUE TITLE
Add indexes on the Prod environment

### ISSUE THREAD

**Issue by vschernoff** [protofire/filecoin-CID-checker#136]
The problem: loading pages from Mongo: reported by Arsenii in the Slack #filecoin-internal
Solution: indexes added manually on prod

**Comment by plcgi1** [comment]
Indexes added 
Changelog
1. Added migration flow to BE
2. Migration flow added to CI/CD
3. All stuff on
https://wallaby.filecoin.tools/
https://calibration.filecoin.tools/
https://filecoin.tools/
