### ISSUE TITLE
UI / UX design

### ISSUE THREAD

**Issue by vschernoff** [protofire/filecoin-CID-checker#15]
Create mock-up

**Comment by pavel-kosobutskiy** [comment]
I finalized design, uploaded it to Zeplin and invited Mariano to Zeplin-project (mariano.aguero@altoros.com).

List:
https://invis.io/7BXSDIBYG82#/422711677_List

Popup:
https://invis.io/7BXSDIBYG82#/422711675_Details

Guidelines:
https://invis.io/7BXSDIBYG82#/422711676_Guidelines
