### ISSUE TITLE
Enhance  Responsive design

### ISSUE THREAD

**Issue by ToshkaM** [protofire/filecoin-CID-checker#24]
1. Open Main screen in browser (Chrome, f.ex.)
2. Resize browser window 

Actual Results: screen not properly resized - see the example screenshot

![image](https://user-images.githubusercontent.com/1901606/86602200-fee53080-bfaa-11ea-9e1d-4e15180b01f7.png)

Expected Results: screen fully resized

**Comment by vschernoff** [comment]
Mismatch of some elements:
![image](https://user-images.githubusercontent.com/38105183/88384211-aa1c2500-cdb4-11ea-9b34-ed81fdb2b385.png)
