### ISSUE TITLE
Deal does not show up in filecoin-CID-checker

### ISSUE THREAD

**Issue by ethanwu155** [protofire/filecoin-CID-checker#57]
I stored a file on FileCoin and on Lotus it reads `StorageDealSealing`. I went to check to see if it shows up in FileCoin CID Checker however it is empty. Not sure if the website it is down or not.

I have attached a screen shot of `lotus client list-deals` and the screenshot of the website. This is for deal 1364547.

<img width="629" alt="Screen Shot 2020-11-20 at 9 24 26 AM" src="https://user-images.githubusercontent.com/17772957/99751021-60eaa080-2b1c-11eb-9a81-8f5fc9214371.png">
<img width="1280" alt="Screen Shot 2020-11-20 at 10 37 04 AM" src="https://user-images.githubusercontent.com/17772957/99751028-62b46400-2b1c-11eb-88bb-43178599c7f8.png">

**Comment by ArseniiPetrovich** [comment]
Website was down at that time. Not relevant, closing.
